// generated 2009/4/29 14:49:50 EIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/program/pm_server/src/pm_server.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//main_window.hh and.//main_window.cc

#ifndef _MAIN_WINDOW_GLADE_HH
#  define _MAIN_WINDOW_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/button.h>
#include <gtkmm/label.h>
#include <gtkmm/treeview.h>
#include <gtkmm/statusbar.h>

class main_window_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * main_window;
        class Gtk::Button * button_connect;
        class Gtk::Label * label_kw;
        class Gtk::Label * label_kva;
        class Gtk::Label * label_kvar;
        class Gtk::Label * label_kwh;
        class Gtk::Label * label_kvah;
        class Gtk::Label * label_kvarh;
        class Gtk::Label * label_ampl1;
        class Gtk::Label * label_ampl2;
        class Gtk::Label * label_ampl3;
        class Gtk::Label * label_ampn;
        class Gtk::Label * label_frek;
        class Gtk::Label * label_cospi;
        class Gtk::Label * label22;
        class Gtk::Label * label_vl1l2;
        class Gtk::Label * label_vl2l3;
        class Gtk::Label * label_vl1l3;
        class Gtk::Label * label_voltl1n;
        class Gtk::Label * label_voltl2n;
        class Gtk::Label * label_voltl3n;
        class Gtk::Label * label_vll;
        class Gtk::Label * label_vln;
        class Gtk::Label * label_ampr;
        class Gtk::TreeView * list_pm;
        class Gtk::Statusbar * statusbar1;
protected:
        
        main_window_glade();
        
        ~main_window_glade();
private:
        virtual void on_button_connect_clicked() = 0;
        virtual void on_button_1_clicked() = 0;
        virtual void on_button_2_clicked() = 0;
        virtual void on_button_3_clicked() = 0;
        virtual void on_button_4_clicked() = 0;
        virtual void on_button_5_clicked() = 0;
};
#endif
