// generated 2008/10/17 18:39:25 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/program/pm_server/src/pm_server.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//win_pm_server.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "win_pm_server_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>

win_pm_server_glade::win_pm_server_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  win_pm_server = this;
   gmm_data = new GlademmData(get_accel_group());
   win_pm_server->set_title(_("PM Server"));
   win_pm_server->set_default_size(500,400);
   win_pm_server->set_modal(false);
   win_pm_server->property_window_position().set_value(Gtk::WIN_POS_NONE);
   win_pm_server->set_resizable(true);
   win_pm_server->property_destroy_with_parent().set_value(false);
   win_pm_server->show();
}

win_pm_server_glade::~win_pm_server_glade()
{  delete gmm_data;
}
