// generated 2008/11/21 11:40:55 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dialog_file_sumber.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dialog_file_sumber_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/box.h>

dialog_file_sumber_glade::dialog_file_sumber_glade(
)
{  
   
   Gtk::Dialog *dialog_file_sumber = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *cancelbutton8 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *okbutton8 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   tree_file_sumber = Gtk::manage(new class Gtk::TreeView());
   
   Gtk::ScrolledWindow *scrolledwindow15 = Gtk::manage(new class Gtk::ScrolledWindow());
   button_edit = Gtk::manage(new class Gtk::Button(_("_Edit"), true));
   button_tambah = Gtk::manage(new class Gtk::Button(_("_Tambah"), true));
   button_hapus = Gtk::manage(new class Gtk::Button(_("_Hapus"), true));
   
   Gtk::VButtonBox *vbuttonbox1 = Gtk::manage(new class Gtk::VButtonBox(Gtk::BUTTONBOX_START, 7));
   Gtk::HBox *hbox12 = Gtk::manage(new class Gtk::HBox(false, 0));
   cancelbutton8->set_flags(Gtk::CAN_FOCUS);
   cancelbutton8->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton8->set_relief(Gtk::RELIEF_NORMAL);
   okbutton8->set_flags(Gtk::CAN_FOCUS);
   okbutton8->set_flags(Gtk::CAN_DEFAULT);
   okbutton8->set_relief(Gtk::RELIEF_NORMAL);
   dialog_file_sumber->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   tree_file_sumber->set_flags(Gtk::CAN_FOCUS);
   tree_file_sumber->set_headers_visible(true);
   tree_file_sumber->set_rules_hint(false);
   tree_file_sumber->set_reorderable(false);
   tree_file_sumber->set_enable_search(true);
   scrolledwindow15->set_flags(Gtk::CAN_FOCUS);
   scrolledwindow15->set_shadow_type(Gtk::SHADOW_IN);
   scrolledwindow15->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow15->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow15->add(*tree_file_sumber);
   button_edit->set_flags(Gtk::CAN_FOCUS);
   button_edit->set_flags(Gtk::CAN_DEFAULT);
   button_edit->set_relief(Gtk::RELIEF_NORMAL);
   button_tambah->set_flags(Gtk::CAN_FOCUS);
   button_tambah->set_flags(Gtk::CAN_DEFAULT);
   button_tambah->set_relief(Gtk::RELIEF_NORMAL);
   button_hapus->set_flags(Gtk::CAN_FOCUS);
   button_hapus->set_flags(Gtk::CAN_DEFAULT);
   button_hapus->set_relief(Gtk::RELIEF_NORMAL);
   vbuttonbox1->set_border_width(10);
   vbuttonbox1->pack_start(*button_edit);
   vbuttonbox1->pack_start(*button_tambah);
   vbuttonbox1->pack_start(*button_hapus);
   hbox12->pack_start(*scrolledwindow15);
   hbox12->pack_start(*vbuttonbox1, Gtk::PACK_SHRINK, 0);
   dialog_file_sumber->get_vbox()->set_homogeneous(false);
   dialog_file_sumber->get_vbox()->set_spacing(0);
   dialog_file_sumber->get_vbox()->pack_start(*hbox12);
   dialog_file_sumber->set_title(_("Setting File Sumber"));
   dialog_file_sumber->set_modal(false);
   dialog_file_sumber->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dialog_file_sumber->set_resizable(true);
   dialog_file_sumber->property_destroy_with_parent().set_value(false);
   dialog_file_sumber->set_has_separator(true);
   dialog_file_sumber->add_action_widget(*cancelbutton8, -6);
   dialog_file_sumber->add_action_widget(*okbutton8, -5);
   cancelbutton8->show();
   okbutton8->show();
   tree_file_sumber->show();
   scrolledwindow15->show();
   button_edit->show();
   button_tambah->show();
   button_hapus->show();
   vbuttonbox1->show();
   hbox12->show();
   dialog_file_sumber->show();
}

dialog_file_sumber_glade::~dialog_file_sumber_glade()
{  delete gmm_data;
}
