// generated 2008/11/21 11:40:55 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dialog_file_sumber.hh and.//dialog_file_sumber.cc

#ifndef _DIALOG_FILE_SUMBER_GLADE_HH
#  define _DIALOG_FILE_SUMBER_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/treeview.h>
#include <gtkmm/button.h>

class dialog_file_sumber_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::TreeView * tree_file_sumber;
        class Gtk::Button * button_edit;
        class Gtk::Button * button_tambah;
        class Gtk::Button * button_hapus;
protected:
        
        dialog_file_sumber_glade();
        
        ~dialog_file_sumber_glade();
};
#endif
