// generated 2008/7/17 14:47:00 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Documents/Program/MonitaApp/src/db_dialog.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dialog1.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dialog1_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>

dialog1_glade::dialog1_glade(
)
{  dialog1 = this;
   gmm_data = new GlademmData(get_accel_group());
   cancelbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   okbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   entry4 = Gtk::manage(new class Gtk::Entry());
   entry5 = Gtk::manage(new class Gtk::Entry());
   entry6 = Gtk::manage(new class Gtk::Entry());
   label4 = Gtk::manage(new class Gtk::Label(_("label4")));
   label5 = Gtk::manage(new class Gtk::Label(_("label5")));
   label6 = Gtk::manage(new class Gtk::Label(_("label6")));
   table1 = Gtk::manage(new class Gtk::Table(2, 2, false));
   label1 = Gtk::manage(new class Gtk::Label(_("<b>frame1</b>")));
   frame1 = Gtk::manage(new class Gtk::Frame());
   cancelbutton1->set_flags(Gtk::CAN_FOCUS);
   cancelbutton1->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton1->set_relief(Gtk::RELIEF_NORMAL);
   okbutton1->set_flags(Gtk::CAN_FOCUS);
   okbutton1->set_flags(Gtk::CAN_DEFAULT);
   okbutton1->set_relief(Gtk::RELIEF_NORMAL);
   dialog1->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   entry4->set_flags(Gtk::CAN_FOCUS);
   entry4->set_visibility(true);
   entry4->set_editable(true);
   entry4->set_max_length(0);
   entry4->set_text(_(""));
   entry4->set_has_frame(true);
   entry4->set_activates_default(false);
   entry5->set_flags(Gtk::CAN_FOCUS);
   entry5->set_visibility(true);
   entry5->set_editable(true);
   entry5->set_max_length(0);
   entry5->set_text(_(""));
   entry5->set_has_frame(true);
   entry5->set_activates_default(false);
   entry6->set_flags(Gtk::CAN_FOCUS);
   entry6->set_visibility(true);
   entry6->set_editable(true);
   entry6->set_max_length(0);
   entry6->set_text(_(""));
   entry6->set_has_frame(true);
   entry6->set_activates_default(false);
   label4->set_alignment(0,0.5);
   label4->set_padding(0,0);
   label4->set_justify(Gtk::JUSTIFY_LEFT);
   label4->set_line_wrap(false);
   label4->set_use_markup(false);
   label4->set_selectable(false);
   label5->set_alignment(0,0.5);
   label5->set_padding(0,0);
   label5->set_justify(Gtk::JUSTIFY_LEFT);
   label5->set_line_wrap(false);
   label5->set_use_markup(false);
   label5->set_selectable(false);
   label6->set_alignment(0,0.5);
   label6->set_padding(0,0);
   label6->set_justify(Gtk::JUSTIFY_LEFT);
   label6->set_line_wrap(false);
   label6->set_use_markup(false);
   label6->set_selectable(false);
   table1->set_row_spacings(0);
   table1->set_col_spacings(0);
   table1->attach(*entry4, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*entry5, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*entry6, 1, 2, 2, 3, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label4, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label5, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label6, 0, 1, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   label1->set_alignment(0.5,0.5);
   label1->set_padding(0,0);
   label1->set_justify(Gtk::JUSTIFY_LEFT);
   label1->set_line_wrap(false);
   label1->set_use_markup(true);
   label1->set_selectable(false);
   frame1->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame1->set_label_align(0,0.5);
   frame1->add(*table1);
   frame1->set_label_widget(*label1);
   dialog1->get_vbox()->set_homogeneous(false);
   dialog1->get_vbox()->set_spacing(0);
   dialog1->get_vbox()->pack_start(*frame1);
   dialog1->set_title(_("dialog1"));
   dialog1->set_modal(false);
   dialog1->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dialog1->set_resizable(true);
   dialog1->property_destroy_with_parent().set_value(false);
   dialog1->set_has_separator(true);
   dialog1->add_action_widget(*cancelbutton1, -6);
   dialog1->add_action_widget(*okbutton1, -5);
   cancelbutton1->show();
   okbutton1->show();
   entry4->show();
   entry5->show();
   entry6->show();
   label4->show();
   label5->show();
   label6->show();
   table1->show();
   label1->show();
   frame1->show();
   dialog1->show();
}

dialog1_glade::~dialog1_glade()
{  delete gmm_data;
}
