// generated 2008/8/1 21:06:21 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Documents/Program/MonitaApp/src/db_dialog.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dialog_sumber.hh and.//dialog_sumber.cc

#ifndef _DIALOG_SUMBER_GLADE_HH
#  define _DIALOG_SUMBER_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/treeview.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/label.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#include <gtkmm/box.h>

class dialog_sumber_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * dialog_sumber;
        class Gtk::Button * cancelbutton2;
        class Gtk::Button * okbutton2;
        class Gtk::TreeView * treeview2;
        class Gtk::ScrolledWindow * scrolledwindow1;
        class Gtk::Button * button_tambah;
        class Gtk::Button * button_hapus;
        class Gtk::Button * button_edit;
        class Gtk::VButtonBox * vbuttonbox1;
        class Gtk::Button * button_koneksi;
        class Gtk::VButtonBox * vbuttonbox2;
        class Gtk::Label * label_info;
        class Gtk::Alignment * alignment2;
        class Gtk::Label * label11;
        class Gtk::Frame * frame3;
        class Gtk::VBox * vbox1;
        class Gtk::HBox * hbox2;
        class Gtk::Alignment * alignment1;
        class Gtk::Label * label10;
        class Gtk::Frame * frame2;
        class Gtk::HBox * hbox1;
protected:
        
        dialog_sumber_glade();
        
        ~dialog_sumber_glade();
private:
        virtual void on_button_tambah_clicked() = 0;
        virtual void on_button_hapus_clicked() = 0;
        virtual void on_button_edit_clicked() = 0;
        virtual void on_button_koneksi_clicked() = 0;
};
#endif
