// generated 2008/10/14 15:25:24 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_report.hh and.//dlg_report.cc

#ifndef _DLG_REPORT_GLADE_HH
#  define _DLG_REPORT_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/tooltips.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/treeview.h>
#include <gtkmm/spinbutton.h>

class dlg_report_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
        Gtk::Tooltips _tooltips;
public:
        class Gtk::RadioButton * radio_csv;
        class Gtk::RadioButton * radio_printer;
        class Gtk::TreeView * tree_pilih_titik;
        class Gtk::SpinButton * spin_tanggal;
        class Gtk::SpinButton * spin_bulan;
        class Gtk::SpinButton * spin_tahun;
protected:
        
        dlg_report_glade();
        
        ~dlg_report_glade();
private:
        virtual void on_button_cetak_clicked() = 0;
        virtual void on_button_open_kalender_clicked() = 0;
        virtual void on_button_tanggal_apply_clicked() = 0;
};
#endif
