// generated 2008/10/14 15:25:24 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_report.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dlg_report_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/image.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/frame.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/adjustment.h>
#include <gtkmm/separator.h>

dlg_report_glade::dlg_report_glade(
)
{  
   
   Gtk::Dialog *dlg_report = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *cancelbutton7 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *okbutton7 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   Gtk::Image *image62 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-print"), Gtk::IconSize(4)));
   Gtk::Label *label55 = Gtk::manage(new class Gtk::Label(_("Buat Laporan")));
   Gtk::HBox *hbox10 = Gtk::manage(new class Gtk::HBox(false, 2));
   Gtk::Alignment *alignment19 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 0, 0));
   Gtk::Button *button_cetak = Gtk::manage(new class Gtk::Button());
   Gtk::RadioButton::Group _RadioBGroup_radio_csv;
   radio_csv = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_csv, _("File CSV (Excel/Spreadsheet)")));
   radio_printer = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_csv, _("Printer")));
   
   Gtk::VBox *vbox8 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Alignment *alignment16 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label51 = Gtk::manage(new class Gtk::Label(_("Pilihan Media")));
   Gtk::Frame *frame11 = Gtk::manage(new class Gtk::Frame());
   tree_pilih_titik = Gtk::manage(new class Gtk::TreeView());
   
   Gtk::ScrolledWindow *scrolledwindow14 = Gtk::manage(new class Gtk::ScrolledWindow());
   Gtk::Alignment *alignment17 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label52 = Gtk::manage(new class Gtk::Label(_("Pilihan Titik Ukur")));
   Gtk::Frame *frame12 = Gtk::manage(new class Gtk::Frame());
   Gtk::Image *image63 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-index"), Gtk::IconSize(4)));
   Gtk::Button *button5 = Gtk::manage(new class Gtk::Button());
   Gtk::Adjustment *spin_tanggal_adj = Gtk::manage(new class Gtk::Adjustment(1, 1, 31, 1, 10, 10));
   spin_tanggal = Gtk::manage(new class Gtk::SpinButton(*spin_tanggal_adj, 1, 0));
   
   Gtk::Adjustment *spin_bulan_adj = Gtk::manage(new class Gtk::Adjustment(1, 1, 12, 1, 10, 10));
   spin_bulan = Gtk::manage(new class Gtk::SpinButton(*spin_bulan_adj, 1, 0));
   
   Gtk::Adjustment *spin_tahun_adj = Gtk::manage(new class Gtk::Adjustment(2007, 2007, 2020, 1, 10, 10));
   spin_tahun = Gtk::manage(new class Gtk::SpinButton(*spin_tahun_adj, 1, 0));
   
   Gtk::Image *image64 = Gtk::manage(new class Gtk::Image(Gtk::StockID("gtk-apply"), Gtk::IconSize(4)));
   Gtk::Button *button6 = Gtk::manage(new class Gtk::Button());
   Gtk::HSeparator *hseparator3 = Gtk::manage(new class Gtk::HSeparator());
   Gtk::HBox *hbox11 = Gtk::manage(new class Gtk::HBox(false, 0));
   Gtk::Alignment *alignment18 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::VBox *vbox9 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label53 = Gtk::manage(new class Gtk::Label(_("Waktu")));
   Gtk::Frame *frame13 = Gtk::manage(new class Gtk::Frame());
   Gtk::VBox *vbox7 = Gtk::manage(new class Gtk::VBox(false, 0));
   cancelbutton7->set_flags(Gtk::CAN_FOCUS);
   cancelbutton7->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton7->add_accelerator("clicked", gmm_data->getAccelGroup(), GDK_Escape, Gdk::ModifierType(0), Gtk::ACCEL_VISIBLE);
   cancelbutton7->set_relief(Gtk::RELIEF_NORMAL);
   okbutton7->set_flags(Gtk::CAN_FOCUS);
   okbutton7->set_flags(Gtk::CAN_DEFAULT);
   okbutton7->add_accelerator("clicked", gmm_data->getAccelGroup(), GDK_Return, Gdk::ModifierType(0), Gtk::ACCEL_VISIBLE);
   okbutton7->set_relief(Gtk::RELIEF_NORMAL);
   image62->set_alignment(0.5,0.5);
   image62->set_padding(0,0);
   label55->set_alignment(0.5,0.5);
   label55->set_padding(0,0);
   label55->set_justify(Gtk::JUSTIFY_LEFT);
   label55->set_line_wrap(false);
   label55->set_use_markup(false);
   label55->set_selectable(false);
   hbox10->pack_start(*image62, Gtk::PACK_SHRINK, 0);
   hbox10->pack_start(*label55, Gtk::PACK_SHRINK, 0);
   alignment19->add(*hbox10);
   button_cetak->set_flags(Gtk::CAN_FOCUS);
   button_cetak->set_flags(Gtk::CAN_DEFAULT);
   button_cetak->set_relief(Gtk::RELIEF_NORMAL);
   button_cetak->add(*alignment19);
   dlg_report->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   radio_csv->set_flags(Gtk::CAN_FOCUS);
   radio_csv->set_relief(Gtk::RELIEF_NORMAL);
   radio_csv->set_mode(true);
   radio_csv->set_active(false);
   radio_printer->set_flags(Gtk::CAN_FOCUS);
   radio_printer->set_relief(Gtk::RELIEF_NORMAL);
   radio_printer->set_mode(true);
   radio_printer->set_active(false);
   vbox8->pack_start(*radio_csv, Gtk::PACK_SHRINK, 0);
   vbox8->pack_start(*radio_printer, Gtk::PACK_SHRINK, 0);
   alignment16->add(*vbox8);
   label51->set_alignment(0.5,0.5);
   label51->set_padding(0,0);
   label51->set_justify(Gtk::JUSTIFY_LEFT);
   label51->set_line_wrap(false);
   label51->set_use_markup(true);
   label51->set_selectable(false);
   frame11->set_shadow_type(Gtk::SHADOW_IN);
   frame11->set_label_align(0,0.5);
   frame11->add(*alignment16);
   frame11->set_label_widget(*label51);
   tree_pilih_titik->set_size_request(600,300);
   tree_pilih_titik->set_flags(Gtk::CAN_FOCUS);
   tree_pilih_titik->set_headers_visible(true);
   tree_pilih_titik->set_rules_hint(false);
   tree_pilih_titik->set_reorderable(false);
   tree_pilih_titik->set_enable_search(true);
   scrolledwindow14->set_flags(Gtk::CAN_FOCUS);
   scrolledwindow14->set_shadow_type(Gtk::SHADOW_IN);
   scrolledwindow14->set_policy(Gtk::POLICY_ALWAYS, Gtk::POLICY_ALWAYS);
   scrolledwindow14->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow14->add(*tree_pilih_titik);
   alignment17->add(*scrolledwindow14);
   label52->set_alignment(0.5,0.5);
   label52->set_padding(0,0);
   label52->set_justify(Gtk::JUSTIFY_LEFT);
   label52->set_line_wrap(false);
   label52->set_use_markup(true);
   label52->set_selectable(false);
   frame12->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame12->set_label_align(0,0.5);
   frame12->add(*alignment17);
   frame12->set_label_widget(*label52);
   image63->set_alignment(0.5,0.5);
   image63->set_padding(0,0);
   button5->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button5, _("Pilih tanggal"), "");
   button5->set_relief(Gtk::RELIEF_NORMAL);
   button5->add(*image63);
   spin_tanggal->set_flags(Gtk::CAN_FOCUS);
   spin_tanggal->set_update_policy(Gtk::UPDATE_IF_VALID);
   spin_tanggal->set_numeric(false);
   spin_tanggal->set_digits(0);
   spin_tanggal->set_wrap(false);
   spin_bulan->set_flags(Gtk::CAN_FOCUS);
   spin_bulan->set_update_policy(Gtk::UPDATE_IF_VALID);
   spin_bulan->set_numeric(true);
   spin_bulan->set_digits(0);
   spin_bulan->set_wrap(false);
   spin_tahun->set_flags(Gtk::CAN_FOCUS);
   spin_tahun->set_update_policy(Gtk::UPDATE_IF_VALID);
   spin_tahun->set_numeric(true);
   spin_tahun->set_digits(0);
   spin_tahun->set_wrap(false);
   image64->set_alignment(0.5,0.5);
   image64->set_padding(0,0);
   button6->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button6, _("Lihat data sesuai tanggal"), "");
   button6->set_relief(Gtk::RELIEF_NORMAL);
   button6->add(*image64);
   hbox11->pack_start(*button5, Gtk::PACK_SHRINK, 1);
   hbox11->pack_start(*spin_tanggal, Gtk::PACK_SHRINK, 0);
   hbox11->pack_start(*spin_bulan, Gtk::PACK_SHRINK, 0);
   hbox11->pack_start(*spin_tahun, Gtk::PACK_SHRINK, 0);
   hbox11->pack_start(*button6, Gtk::PACK_SHRINK, 0);
   hbox11->pack_start(*hseparator3);
   alignment18->add(*hbox11);
   vbox9->pack_start(*alignment18);
   label53->set_alignment(0.5,0.5);
   label53->set_padding(0,0);
   label53->set_justify(Gtk::JUSTIFY_LEFT);
   label53->set_line_wrap(false);
   label53->set_use_markup(true);
   label53->set_selectable(false);
   frame13->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame13->set_label_align(0,0.5);
   frame13->add(*vbox9);
   frame13->set_label_widget(*label53);
   vbox7->pack_start(*frame11, Gtk::PACK_SHRINK, 0);
   vbox7->pack_start(*frame12);
   vbox7->pack_start(*frame13);
   dlg_report->get_vbox()->set_homogeneous(false);
   dlg_report->get_vbox()->set_spacing(0);
   dlg_report->get_vbox()->pack_start(*vbox7);
   dlg_report->set_title(_("Cetak Laporan"));
   dlg_report->set_modal(false);
   dlg_report->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dlg_report->set_resizable(true);
   dlg_report->property_destroy_with_parent().set_value(false);
   dlg_report->set_has_separator(true);
   dlg_report->add_action_widget(*cancelbutton7, -6);
   dlg_report->add_action_widget(*okbutton7, -5);
   dlg_report->add_action_widget(*button_cetak, 0);
   cancelbutton7->show();
   okbutton7->show();
   image62->show();
   label55->show();
   hbox10->show();
   alignment19->show();
   button_cetak->show();
   radio_csv->show();
   radio_printer->show();
   vbox8->show();
   alignment16->show();
   label51->show();
   frame11->show();
   tree_pilih_titik->show();
   scrolledwindow14->show();
   alignment17->show();
   label52->show();
   frame12->show();
   image63->show();
   button5->show();
   spin_tanggal->show();
   spin_bulan->show();
   spin_tahun->show();
   image64->show();
   button6->show();
   hseparator3->show();
   hbox11->show();
   alignment18->show();
   vbox9->show();
   label53->show();
   frame13->show();
   vbox7->show();
   dlg_report->show();
   button_cetak->signal_clicked().connect(SigC::slot(*this, &dlg_report_glade::on_button_cetak_clicked), false);
   button5->signal_clicked().connect(SigC::slot(*this, &dlg_report_glade::on_button_open_kalender_clicked), false);
   button6->signal_clicked().connect(SigC::slot(*this, &dlg_report_glade::on_button_tanggal_apply_clicked), false);
}

dlg_report_glade::~dlg_report_glade()
{  delete gmm_data;
}
