// generated 2008/8/9 10:44:33 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_posting_data.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_edit_post.hh and.//dlg_edit_post.cc

#ifndef _DLG_EDIT_POST_GLADE_HH
#  define _DLG_EDIT_POST_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/spinbutton.h>

class dlg_edit_post_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::RadioButton * radio_post_localdisplay;
        class Gtk::RadioButton * radio_post_gsm;
        class Gtk::CheckButton * check_post_aktif;
        class Gtk::Entry * entry_ip_address;
        class Gtk::Entry * entry_ip_port;
        class Gtk::SpinButton * spin_periode;
        class Gtk::Entry * entry_nama_post;
        class Gtk::Entry * entry_keterangan;
protected:
        
        dlg_edit_post_glade();
        
        ~dlg_edit_post_glade();
private:
        virtual void on_parameter_changed() = 0;
};
#endif
