// generated 2008/9/5 11:36:18 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_edit_dept.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dlg_edit_dept_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/table.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#include <gtkmm/box.h>

dlg_edit_dept_glade::dlg_edit_dept_glade(
)
{  
   
   Gtk::Dialog *dlg_edit_dept = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *cancelbutton4 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *okbutton4 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   entry_nama = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label20 = Gtk::manage(new class Gtk::Label(_("Nama Departemen")));
   entry_gambar = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label21 = Gtk::manage(new class Gtk::Label(_("Gambar")));
   textview_keterangan = Gtk::manage(new class Gtk::TextView());
   
   Gtk::ScrolledWindow *scrolledwindow11 = Gtk::manage(new class Gtk::ScrolledWindow());
   button_browse = Gtk::manage(new class Gtk::Button(_("_Pilih Gambar"), true));
   
   Gtk::Label *label22 = Gtk::manage(new class Gtk::Label(_("Keterangan")));
   Gtk::Table *table4 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment9 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label19 = Gtk::manage(new class Gtk::Label(_("Edit/Tambah Departemen")));
   Gtk::Frame *frame5 = Gtk::manage(new class Gtk::Frame());
   cancelbutton4->set_flags(Gtk::CAN_FOCUS);
   cancelbutton4->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton4->add_accelerator("clicked", gmm_data->getAccelGroup(), GDK_Escape, Gdk::ModifierType(0), Gtk::ACCEL_VISIBLE);
   cancelbutton4->set_relief(Gtk::RELIEF_NORMAL);
   okbutton4->set_flags(Gtk::CAN_FOCUS);
   okbutton4->set_flags(Gtk::CAN_DEFAULT);
   okbutton4->add_accelerator("clicked", gmm_data->getAccelGroup(), GDK_Return, Gdk::ModifierType(0), Gtk::ACCEL_VISIBLE);
   okbutton4->set_relief(Gtk::RELIEF_NORMAL);
   dlg_edit_dept->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   entry_nama->set_flags(Gtk::CAN_FOCUS);
   entry_nama->set_visibility(true);
   entry_nama->set_editable(true);
   entry_nama->set_max_length(0);
   entry_nama->set_text(_(""));
   entry_nama->set_has_frame(true);
   entry_nama->set_activates_default(false);
   label20->set_alignment(0,0.5);
   label20->set_padding(0,0);
   label20->set_justify(Gtk::JUSTIFY_LEFT);
   label20->set_line_wrap(false);
   label20->set_use_markup(false);
   label20->set_selectable(false);
   entry_gambar->set_flags(Gtk::CAN_FOCUS);
   entry_gambar->set_visibility(true);
   entry_gambar->set_editable(true);
   entry_gambar->set_max_length(0);
   entry_gambar->set_text(_(""));
   entry_gambar->set_has_frame(true);
   entry_gambar->set_activates_default(false);
   label21->set_alignment(0,0.5);
   label21->set_padding(0,0);
   label21->set_justify(Gtk::JUSTIFY_LEFT);
   label21->set_line_wrap(false);
   label21->set_use_markup(false);
   label21->set_selectable(false);
   textview_keterangan->set_flags(Gtk::CAN_FOCUS);
   textview_keterangan->set_editable(true);
   textview_keterangan->set_cursor_visible(true);
   textview_keterangan->set_pixels_above_lines(0);
   textview_keterangan->set_pixels_below_lines(0);
   textview_keterangan->set_pixels_inside_wrap(0);
   textview_keterangan->set_left_margin(0);
   textview_keterangan->set_right_margin(0);
   textview_keterangan->set_indent(0);
   textview_keterangan->set_wrap_mode(Gtk::WRAP_NONE);
   textview_keterangan->set_justification(Gtk::JUSTIFY_LEFT);
   scrolledwindow11->set_flags(Gtk::CAN_FOCUS);
   scrolledwindow11->set_shadow_type(Gtk::SHADOW_IN);
   scrolledwindow11->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow11->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow11->add(*textview_keterangan);
   button_browse->set_flags(Gtk::CAN_FOCUS);
   button_browse->set_relief(Gtk::RELIEF_NORMAL);
   label22->set_alignment(0,0.5);
   label22->set_padding(0,0);
   label22->set_justify(Gtk::JUSTIFY_LEFT);
   label22->set_line_wrap(false);
   label22->set_use_markup(false);
   label22->set_selectable(false);
   table4->set_row_spacings(0);
   table4->set_col_spacings(0);
   table4->attach(*entry_nama, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table4->attach(*label20, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table4->attach(*entry_gambar, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table4->attach(*label21, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table4->attach(*scrolledwindow11, 1, 2, 2, 3, Gtk::FILL, Gtk::EXPAND|Gtk::FILL, 0, 0);
   table4->attach(*button_browse, 2, 3, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table4->attach(*label22, 0, 1, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   alignment9->add(*table4);
   label19->set_alignment(0.5,0.5);
   label19->set_padding(0,0);
   label19->set_justify(Gtk::JUSTIFY_LEFT);
   label19->set_line_wrap(false);
   label19->set_use_markup(true);
   label19->set_selectable(false);
   frame5->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame5->set_label_align(0,0.5);
   frame5->add(*alignment9);
   frame5->set_label_widget(*label19);
   dlg_edit_dept->get_vbox()->set_homogeneous(false);
   dlg_edit_dept->get_vbox()->set_spacing(0);
   dlg_edit_dept->get_vbox()->pack_start(*frame5);
   dlg_edit_dept->set_title(_("Departemen"));
   dlg_edit_dept->set_modal(true);
   dlg_edit_dept->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dlg_edit_dept->set_resizable(true);
   dlg_edit_dept->property_destroy_with_parent().set_value(true);
   dlg_edit_dept->set_has_separator(true);
   dlg_edit_dept->add_action_widget(*cancelbutton4, -6);
   dlg_edit_dept->add_action_widget(*okbutton4, -5);
   cancelbutton4->show();
   okbutton4->show();
   entry_nama->show();
   label20->show();
   entry_gambar->show();
   label21->show();
   textview_keterangan->show();
   scrolledwindow11->show();
   button_browse->show();
   label22->show();
   table4->show();
   alignment9->show();
   label19->show();
   frame5->show();
   dlg_edit_dept->show();
   okbutton4->signal_clicked().connect(SigC::slot(*this, &dlg_edit_dept_glade::on_okbutton4_clicked), false);
}

dlg_edit_dept_glade::~dlg_edit_dept_glade()
{  delete gmm_data;
}
