// generated 2008/9/8 12:33:45 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_edit_data.hh and.//dlg_edit_data.cc

#ifndef _DLG_EDIT_DATA_GLADE_HH
#  define _DLG_EDIT_DATA_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/entry.h>
#include <gtkmm/label.h>

class dlg_edit_data_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Entry * entry_data;
        class Gtk::Label * label_waktu;
        class Gtk::Label * label_sumber_data;
        class Gtk::Label * label_no_board;
        class Gtk::Label * label_nomer_kanal;
protected:
        
        dlg_edit_data_glade();
        
        ~dlg_edit_data_glade();
};
#endif
