// generated 2008/9/5 11:36:18 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_kalender.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dlg_kalender_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/box.h>

dlg_kalender_glade::dlg_kalender_glade(
)
{  
   
   Gtk::Dialog *dlg_kalender = this;
   gmm_data = new GlademmData(get_accel_group());
   cancelbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   okbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   calendar1 = Gtk::manage(new class Gtk::Calendar());
   cancelbutton1->set_flags(Gtk::CAN_FOCUS);
   cancelbutton1->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton1->add_accelerator("clicked", gmm_data->getAccelGroup(), GDK_Escape, Gdk::ModifierType(0), Gtk::ACCEL_VISIBLE);
   cancelbutton1->set_relief(Gtk::RELIEF_NORMAL);
   okbutton1->set_flags(Gtk::CAN_FOCUS);
   okbutton1->set_flags(Gtk::CAN_DEFAULT);
   okbutton1->add_accelerator("clicked", gmm_data->getAccelGroup(), GDK_Return, Gdk::ModifierType(0), Gtk::ACCEL_VISIBLE);
   okbutton1->set_relief(Gtk::RELIEF_NORMAL);
   dlg_kalender->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   calendar1->set_flags(Gtk::CAN_FOCUS);
   calendar1->display_options(Gtk::CALENDAR_SHOW_HEADING|Gtk::CALENDAR_SHOW_DAY_NAMES);
   dlg_kalender->get_vbox()->set_homogeneous(false);
   dlg_kalender->get_vbox()->set_spacing(0);
   dlg_kalender->get_vbox()->pack_start(*calendar1);
   dlg_kalender->set_title(_("Set Tanggal"));
   dlg_kalender->set_modal(false);
   dlg_kalender->property_window_position().set_value(Gtk::WIN_POS_MOUSE);
   dlg_kalender->set_resizable(true);
   dlg_kalender->property_destroy_with_parent().set_value(false);
   dlg_kalender->set_has_separator(true);
   dlg_kalender->add_action_widget(*cancelbutton1, -6);
   dlg_kalender->add_action_widget(*okbutton1, -5);
   cancelbutton1->show();
   okbutton1->show();
   calendar1->show();
   dlg_kalender->show();
}

dlg_kalender_glade::~dlg_kalender_glade()
{  delete gmm_data;
}
