// generated 2008/9/12 23:20:51 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_koneksi_sumber.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_koneksi_sumber.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dlg_koneksi_sumber_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#include <gtkmm/scrolledwindow.h>

dlg_koneksi_sumber_glade::dlg_koneksi_sumber_glade(
)
{  dlg_koneksi_sumber = this;
   gmm_data = new GlademmData(get_accel_group());
   okbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   label_nama_sumber = Gtk::manage(new class Gtk::Label(_("label5")));
   
   Gtk::Label *label4 = Gtk::manage(new class Gtk::Label(_("Nomer ")));
   combo_port = Gtk::manage(new class Gtk::ComboBox());
   
   Gtk::HBox *hbox1 = Gtk::manage(new class Gtk::HBox(false, 0));
   Gtk::Alignment *alignment2 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label2 = Gtk::manage(new class Gtk::Label(_("<b>Nomer Board/Modul</b>")));
   Gtk::Frame *frame2 = Gtk::manage(new class Gtk::Frame());
   treeview2 = Gtk::manage(new class Gtk::TreeView());
   
   Gtk::ScrolledWindow *scrolledwindow1 = Gtk::manage(new class Gtk::ScrolledWindow());
   Gtk::Alignment *alignment3 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label3 = Gtk::manage(new class Gtk::Label(_("<b>Koneksi Titik Ukur</b>")));
   Gtk::Frame *frame3 = Gtk::manage(new class Gtk::Frame());
   Gtk::VBox *vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Alignment *alignment1 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label1 = Gtk::manage(new class Gtk::Label(_("<b>-</b>")));
   Gtk::Frame *frame1 = Gtk::manage(new class Gtk::Frame());
   okbutton1->set_flags(Gtk::CAN_FOCUS);
   okbutton1->set_flags(Gtk::CAN_DEFAULT);
   okbutton1->set_relief(Gtk::RELIEF_NORMAL);
   dlg_koneksi_sumber->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_SPREAD);
   label_nama_sumber->set_alignment(0.5,0.5);
   label_nama_sumber->set_padding(0,0);
   label_nama_sumber->set_justify(Gtk::JUSTIFY_LEFT);
   label_nama_sumber->set_line_wrap(false);
   label_nama_sumber->set_use_markup(true);
   label_nama_sumber->set_selectable(false);
   label4->set_alignment(0.5,0.5);
   label4->set_padding(0,0);
   label4->set_justify(Gtk::JUSTIFY_LEFT);
   label4->set_line_wrap(false);
   label4->set_use_markup(false);
   label4->set_selectable(false);
   hbox1->pack_start(*label4, Gtk::PACK_SHRINK, 0);
   hbox1->pack_start(*combo_port);
   alignment2->add(*hbox1);
   label2->set_alignment(0.5,0.5);
   label2->set_padding(0,0);
   label2->set_justify(Gtk::JUSTIFY_LEFT);
   label2->set_line_wrap(false);
   label2->set_use_markup(true);
   label2->set_selectable(false);
   frame2->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame2->set_label_align(0,0.5);
   frame2->add(*alignment2);
   frame2->set_label_widget(*label2);
   treeview2->set_flags(Gtk::CAN_FOCUS);
   treeview2->set_headers_visible(true);
   treeview2->set_rules_hint(false);
   treeview2->set_reorderable(false);
   treeview2->set_enable_search(true);
   scrolledwindow1->set_flags(Gtk::CAN_FOCUS);
   scrolledwindow1->set_shadow_type(Gtk::SHADOW_IN);
   scrolledwindow1->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow1->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow1->add(*treeview2);
   alignment3->add(*scrolledwindow1);
   label3->set_alignment(0.5,0.5);
   label3->set_padding(0,0);
   label3->set_justify(Gtk::JUSTIFY_LEFT);
   label3->set_line_wrap(false);
   label3->set_use_markup(true);
   label3->set_selectable(false);
   frame3->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame3->set_label_align(0,0.5);
   frame3->add(*alignment3);
   frame3->set_label_widget(*label3);
   vbox1->pack_start(*label_nama_sumber, Gtk::PACK_SHRINK, 0);
   vbox1->pack_start(*frame2, Gtk::PACK_SHRINK, 0);
   vbox1->pack_start(*frame3);
   alignment1->add(*vbox1);
   label1->set_alignment(0.5,0.5);
   label1->set_padding(0,0);
   label1->set_justify(Gtk::JUSTIFY_LEFT);
   label1->set_line_wrap(false);
   label1->set_use_markup(true);
   label1->set_selectable(false);
   frame1->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame1->set_label_align(0,0.5);
   frame1->add(*alignment1);
   frame1->set_label_widget(*label1);
   dlg_koneksi_sumber->get_vbox()->set_homogeneous(false);
   dlg_koneksi_sumber->get_vbox()->set_spacing(0);
   dlg_koneksi_sumber->get_vbox()->pack_start(*frame1);
   dlg_koneksi_sumber->set_title(_("Tabel Koneksi"));
   dlg_koneksi_sumber->set_default_size(300,500);
   dlg_koneksi_sumber->set_modal(true);
   dlg_koneksi_sumber->property_window_position().set_value(Gtk::WIN_POS_CENTER_ON_PARENT);
   dlg_koneksi_sumber->set_resizable(true);
   dlg_koneksi_sumber->property_destroy_with_parent().set_value(true);
   dlg_koneksi_sumber->set_has_separator(true);
   dlg_koneksi_sumber->add_action_widget(*okbutton1, -5);
   okbutton1->show();
   label_nama_sumber->show();
   label4->show();
   combo_port->show();
   hbox1->show();
   alignment2->show();
   label2->show();
   frame2->show();
   treeview2->show();
   scrolledwindow1->show();
   alignment3->show();
   label3->show();
   frame3->show();
   vbox1->show();
   alignment1->show();
   label1->show();
   frame1->show();
   dlg_koneksi_sumber->show();
   okbutton1->signal_clicked().connect(SigC::slot(*this, &dlg_koneksi_sumber_glade::on_okbutton1_clicked), false);
   okbutton1->grab_default();
}

dlg_koneksi_sumber_glade::~dlg_koneksi_sumber_glade()
{  delete gmm_data;
}
