// generated 2008/8/9 9:11:45 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_posting_data.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_posting_data.hh and.//dlg_posting_data.cc

#ifndef _DLG_POSTING_DATA_GLADE_HH
#  define _DLG_POSTING_DATA_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/treeview.h>

class dlg_posting_data_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::TreeView * tree_posting;
protected:
        
        dlg_posting_data_glade();
        
        ~dlg_posting_data_glade();
private:
        virtual void on_button_tambah_clicked() = 0;
        virtual void on_button_hapus_clicked() = 0;
        virtual void on_button_edit_clicked() = 0;
};
#endif
