// generated 2008/10/30 8:34:48 CIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_konfigurasi.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_konfigurasi.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dlg_konfigurasi_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/label.h>
#include <gtkmm/separator.h>
#include <gtkmm/table.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#include <gtkmm/adjustment.h>
#include <gtkmm/box.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/notebook.h>

dlg_konfigurasi_glade::dlg_konfigurasi_glade(
)
{  
   
   Gtk::Dialog *dlg_konfigurasi = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *cancelbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *okbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   Gtk::RadioButton::Group _RadioBGroup_radio_mode_server;
   radio_mode_server = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_mode_server, _("Server Data Logging")));
   radio_mode_monitor = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_mode_server, _("Terminal Monitor")));
   
   Gtk::Label *label14 = Gtk::manage(new class Gtk::Label(_("<i>(Untuk pengambilan data)</i>")));
   Gtk::Label *label15 = Gtk::manage(new class Gtk::Label(_("<i>(Untuk memonitor/melihat data)</i>")));
   check_autostart = Gtk::manage(new class Gtk::CheckButton(_("Langsung ambil data saat start")));
   
   Gtk::HSeparator *hseparator1 = Gtk::manage(new class Gtk::HSeparator());
   Gtk::Table *table3 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment2 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label8 = Gtk::manage(new class Gtk::Label(_("Mode ")));
   Gtk::Frame *frame2 = Gtk::manage(new class Gtk::Frame());
   Gtk::Label *label7 = Gtk::manage(new class Gtk::Label(_("Mode Software")));
   Gtk::Label *label_server_mode = Gtk::manage(new class Gtk::Label(_("Periode Siklus Pengambilan Data")));
   Gtk::Label *label4 = Gtk::manage(new class Gtk::Label(_("ms (default 1000)")));
   Gtk::Label *label5 = Gtk::manage(new class Gtk::Label(_("Periode Penyimpanan Data")));
   Gtk::Adjustment *spin_periode_simpan_adj = Gtk::manage(new class Gtk::Adjustment(1, 1, 100, 1, 10, 10));
   spin_periode_simpan = Gtk::manage(new class Gtk::SpinButton(*spin_periode_simpan_adj, 1, 0));
   
   Gtk::Label *label6 = Gtk::manage(new class Gtk::Label(_("menit (default 1)")));
   Gtk::Adjustment *spin_periode_logging_adj = Gtk::manage(new class Gtk::Adjustment(1000, 500, 100000, 500, 10, 10));
   spin_periode_logging = Gtk::manage(new class Gtk::SpinButton(*spin_periode_logging_adj, 1, 0));
   
   Gtk::Table *table1 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment1 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label3 = Gtk::manage(new class Gtk::Label(_("Data Logging")));
   Gtk::Frame *frame1 = Gtk::manage(new class Gtk::Frame());
   Gtk::Label *label10 = Gtk::manage(new class Gtk::Label(_("Refresh Tabel Hasil Pengukuran")));
   Gtk::Label *label11 = Gtk::manage(new class Gtk::Label(_("menit( default 1)")));
   Gtk::Adjustment *spin_refresh_list_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 100, 1, 10, 10));
   spin_refresh_list = Gtk::manage(new class Gtk::SpinButton(*spin_refresh_list_adj, 1, 0));
   
   Gtk::Label *label12 = Gtk::manage(new class Gtk::Label(_("Refresh Grafik")));
   Gtk::Adjustment *spin_refresh_grafik_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 100, 1, 10, 10));
   spin_refresh_grafik = Gtk::manage(new class Gtk::SpinButton(*spin_refresh_grafik_adj, 1, 0));
   
   Gtk::Label *label13 = Gtk::manage(new class Gtk::Label(_("menit (default 1)")));
   Gtk::Table *table2 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment3 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label9 = Gtk::manage(new class Gtk::Label(_("Menampilkan Data")));
   Gtk::Frame *frame3 = Gtk::manage(new class Gtk::Frame());
   Gtk::VBox *vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label1 = Gtk::manage(new class Gtk::Label(_("Pengaturan Waktu")));
   Gtk::Label *label18 = Gtk::manage(new class Gtk::Label(_("Database Temporary")));
   Gtk::Label *label19 = Gtk::manage(new class Gtk::Label(_("hari \n"
		"(1 hari=24jam)")));
   Gtk::Adjustment *spin_periode_db_temp_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 30, 1, 10, 10));
   spin_periode_db_temp = Gtk::manage(new class Gtk::SpinButton(*spin_periode_db_temp_adj, 1, 0));
   
   Gtk::Table *table4 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment4 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label17 = Gtk::manage(new class Gtk::Label(_("Database Setting")));
   Gtk::Frame *frame4 = Gtk::manage(new class Gtk::Frame());
   Gtk::Label *label16 = Gtk::manage(new class Gtk::Label(_("Database Setting")));
   Gtk::CheckButton *checkbutton1 = Gtk::manage(new class Gtk::CheckButton(_("Aktifkan Jurnal")));
   Gtk::RadioButton::Group _RadioBGroup_radiobutton1;
   Gtk::RadioButton *radiobutton1 = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radiobutton1, _("Sederhana")));
   Gtk::RadioButton *radiobutton2 = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radiobutton1, _("Menengah")));
   Gtk::RadioButton *radiobutton3 = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radiobutton1, _("Semuanya")));
   Gtk::VBox *vbox2 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Alignment *alignment6 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label22 = Gtk::manage(new class Gtk::Label(_("")));
   Gtk::Frame *frame6 = Gtk::manage(new class Gtk::Frame());
   Gtk::Table *table5 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment5 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label21 = Gtk::manage(new class Gtk::Label(_("Log/Jurnal")));
   Gtk::Frame *frame5 = Gtk::manage(new class Gtk::Frame());
   Gtk::Label *label20 = Gtk::manage(new class Gtk::Label(_("Log")));
   Gtk::Notebook *notebook1 = Gtk::manage(new class Gtk::Notebook());
   cancelbutton1->set_flags(Gtk::CAN_FOCUS);
   cancelbutton1->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton1->set_relief(Gtk::RELIEF_NORMAL);
   okbutton1->set_flags(Gtk::CAN_FOCUS);
   okbutton1->set_flags(Gtk::CAN_DEFAULT);
   okbutton1->set_relief(Gtk::RELIEF_NORMAL);
   dlg_konfigurasi->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   radio_mode_server->set_flags(Gtk::CAN_FOCUS);
   radio_mode_server->set_relief(Gtk::RELIEF_NORMAL);
   radio_mode_server->set_mode(true);
   radio_mode_server->set_active(false);
   radio_mode_monitor->set_flags(Gtk::CAN_FOCUS);
   radio_mode_monitor->set_relief(Gtk::RELIEF_NORMAL);
   radio_mode_monitor->set_mode(true);
   radio_mode_monitor->set_active(false);
   label14->set_alignment(0,0.5);
   label14->set_padding(0,0);
   label14->set_justify(Gtk::JUSTIFY_RIGHT);
   label14->set_line_wrap(false);
   label14->set_use_markup(true);
   label14->set_selectable(false);
   label15->set_alignment(0,0.5);
   label15->set_padding(0,0);
   label15->set_justify(Gtk::JUSTIFY_RIGHT);
   label15->set_line_wrap(false);
   label15->set_use_markup(true);
   label15->set_selectable(false);
   check_autostart->set_flags(Gtk::CAN_FOCUS);
   check_autostart->set_relief(Gtk::RELIEF_NORMAL);
   check_autostart->set_mode(true);
   check_autostart->set_active(false);
   table3->set_row_spacings(0);
   table3->set_col_spacings(0);
   table3->attach(*radio_mode_server, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*radio_mode_monitor, 0, 1, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*label14, 1, 2, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*label15, 1, 2, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*check_autostart, 1, 2, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table3->attach(*hseparator1, 0, 1, 1, 2, Gtk::FILL, Gtk::FILL, 0, 0);
   alignment2->add(*table3);
   label8->set_alignment(0.5,0.5);
   label8->set_padding(0,0);
   label8->set_justify(Gtk::JUSTIFY_LEFT);
   label8->set_line_wrap(false);
   label8->set_use_markup(true);
   label8->set_selectable(false);
   frame2->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame2->set_label_align(0,0.5);
   frame2->add(*alignment2);
   frame2->set_label_widget(*label8);
   label7->set_alignment(0.5,0.5);
   label7->set_padding(0,0);
   label7->set_justify(Gtk::JUSTIFY_LEFT);
   label7->set_line_wrap(false);
   label7->set_use_markup(false);
   label7->set_selectable(false);
   label_server_mode->set_alignment(0,0.5);
   label_server_mode->set_padding(0,0);
   label_server_mode->set_justify(Gtk::JUSTIFY_LEFT);
   label_server_mode->set_line_wrap(false);
   label_server_mode->set_use_markup(false);
   label_server_mode->set_selectable(false);
   label4->set_alignment(0,0.5);
   label4->set_padding(0,0);
   label4->set_justify(Gtk::JUSTIFY_LEFT);
   label4->set_line_wrap(false);
   label4->set_use_markup(false);
   label4->set_selectable(false);
   label5->set_alignment(0,0.5);
   label5->set_padding(0,0);
   label5->set_justify(Gtk::JUSTIFY_LEFT);
   label5->set_line_wrap(false);
   label5->set_use_markup(false);
   label5->set_selectable(false);
   spin_periode_simpan->set_flags(Gtk::CAN_FOCUS);
   spin_periode_simpan->set_update_policy(Gtk::UPDATE_ALWAYS);
   spin_periode_simpan->set_numeric(false);
   spin_periode_simpan->set_digits(0);
   spin_periode_simpan->set_wrap(false);
   label6->set_alignment(0,0.5);
   label6->set_padding(0,0);
   label6->set_justify(Gtk::JUSTIFY_LEFT);
   label6->set_line_wrap(false);
   label6->set_use_markup(false);
   label6->set_selectable(false);
   spin_periode_logging->set_flags(Gtk::CAN_FOCUS);
   spin_periode_logging->set_update_policy(Gtk::UPDATE_ALWAYS);
   spin_periode_logging->set_numeric(false);
   spin_periode_logging->set_digits(0);
   spin_periode_logging->set_wrap(false);
   table1->set_row_spacings(0);
   table1->set_col_spacings(0);
   table1->attach(*label_server_mode, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label4, 2, 3, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label5, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*spin_periode_simpan, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label6, 2, 3, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*spin_periode_logging, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   alignment1->add(*table1);
   label3->set_alignment(0.5,0.5);
   label3->set_padding(0,0);
   label3->set_justify(Gtk::JUSTIFY_LEFT);
   label3->set_line_wrap(false);
   label3->set_use_markup(true);
   label3->set_selectable(false);
   frame1->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame1->set_label_align(0,0.5);
   frame1->add(*alignment1);
   frame1->set_label_widget(*label3);
   label10->set_alignment(0,0.5);
   label10->set_padding(0,0);
   label10->set_justify(Gtk::JUSTIFY_LEFT);
   label10->set_line_wrap(false);
   label10->set_use_markup(false);
   label10->set_selectable(false);
   label11->set_alignment(0,0.5);
   label11->set_padding(0,0);
   label11->set_justify(Gtk::JUSTIFY_LEFT);
   label11->set_line_wrap(false);
   label11->set_use_markup(false);
   label11->set_selectable(false);
   spin_refresh_list->set_flags(Gtk::CAN_FOCUS);
   spin_refresh_list->set_update_policy(Gtk::UPDATE_ALWAYS);
   spin_refresh_list->set_numeric(false);
   spin_refresh_list->set_digits(0);
   spin_refresh_list->set_wrap(false);
   label12->set_alignment(0,0.5);
   label12->set_padding(0,0);
   label12->set_justify(Gtk::JUSTIFY_LEFT);
   label12->set_line_wrap(false);
   label12->set_use_markup(false);
   label12->set_selectable(false);
   spin_refresh_grafik->set_flags(Gtk::CAN_FOCUS);
   spin_refresh_grafik->set_update_policy(Gtk::UPDATE_ALWAYS);
   spin_refresh_grafik->set_numeric(false);
   spin_refresh_grafik->set_digits(0);
   spin_refresh_grafik->set_wrap(false);
   label13->set_alignment(0,0.5);
   label13->set_padding(0,0);
   label13->set_justify(Gtk::JUSTIFY_LEFT);
   label13->set_line_wrap(false);
   label13->set_use_markup(false);
   label13->set_selectable(false);
   table2->set_row_spacings(0);
   table2->set_col_spacings(0);
   table2->attach(*label10, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*label11, 2, 3, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*spin_refresh_list, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*label12, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*spin_refresh_grafik, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*label13, 2, 3, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   alignment3->add(*table2);
   label9->set_alignment(0.5,0.5);
   label9->set_padding(0,0);
   label9->set_justify(Gtk::JUSTIFY_LEFT);
   label9->set_line_wrap(false);
   label9->set_use_markup(true);
   label9->set_selectable(false);
   frame3->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame3->set_label_align(0,0.5);
   frame3->add(*alignment3);
   frame3->set_label_widget(*label9);
   vbox1->pack_start(*frame1);
   vbox1->pack_start(*frame3);
   label1->set_alignment(0.5,0.5);
   label1->set_padding(0,0);
   label1->set_justify(Gtk::JUSTIFY_LEFT);
   label1->set_line_wrap(false);
   label1->set_use_markup(false);
   label1->set_selectable(false);
   label18->set_alignment(0,0.5);
   label18->set_padding(0,0);
   label18->set_justify(Gtk::JUSTIFY_LEFT);
   label18->set_line_wrap(false);
   label18->set_use_markup(false);
   label18->set_selectable(false);
   label19->set_alignment(0,0.5);
   label19->set_padding(0,0);
   label19->set_justify(Gtk::JUSTIFY_LEFT);
   label19->set_line_wrap(false);
   label19->set_use_markup(false);
   label19->set_selectable(false);
   spin_periode_db_temp->set_flags(Gtk::CAN_FOCUS);
   spin_periode_db_temp->set_update_policy(Gtk::UPDATE_ALWAYS);
   spin_periode_db_temp->set_numeric(false);
   spin_periode_db_temp->set_digits(0);
   spin_periode_db_temp->set_wrap(false);
   table4->set_row_spacings(0);
   table4->set_col_spacings(0);
   table4->attach(*label18, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table4->attach(*label19, 2, 3, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table4->attach(*spin_periode_db_temp, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   alignment4->add(*table4);
   label17->set_alignment(0.5,0.5);
   label17->set_padding(0,0);
   label17->set_justify(Gtk::JUSTIFY_LEFT);
   label17->set_line_wrap(false);
   label17->set_use_markup(true);
   label17->set_selectable(false);
   frame4->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame4->set_label_align(0,0.5);
   frame4->add(*alignment4);
   frame4->set_label_widget(*label17);
   label16->set_alignment(0.5,0.5);
   label16->set_padding(0,0);
   label16->set_justify(Gtk::JUSTIFY_LEFT);
   label16->set_line_wrap(false);
   label16->set_use_markup(false);
   label16->set_selectable(false);
   checkbutton1->set_flags(Gtk::CAN_FOCUS);
   checkbutton1->set_relief(Gtk::RELIEF_NORMAL);
   checkbutton1->set_mode(true);
   checkbutton1->set_active(false);
   radiobutton1->set_sensitive(false);
   radiobutton1->set_flags(Gtk::CAN_FOCUS);
   radiobutton1->set_relief(Gtk::RELIEF_NORMAL);
   radiobutton1->set_mode(true);
   radiobutton1->set_active(false);
   radiobutton2->set_sensitive(false);
   radiobutton2->set_flags(Gtk::CAN_FOCUS);
   radiobutton2->set_relief(Gtk::RELIEF_NORMAL);
   radiobutton2->set_mode(true);
   radiobutton2->set_active(false);
   radiobutton3->set_sensitive(false);
   radiobutton3->set_flags(Gtk::CAN_FOCUS);
   radiobutton3->set_relief(Gtk::RELIEF_NORMAL);
   radiobutton3->set_mode(true);
   radiobutton3->set_active(false);
   vbox2->pack_start(*radiobutton1, Gtk::PACK_SHRINK, 0);
   vbox2->pack_start(*radiobutton2, Gtk::PACK_SHRINK, 0);
   vbox2->pack_start(*radiobutton3, Gtk::PACK_SHRINK, 0);
   alignment6->add(*vbox2);
   label22->set_alignment(0.5,0.5);
   label22->set_padding(0,0);
   label22->set_justify(Gtk::JUSTIFY_LEFT);
   label22->set_line_wrap(false);
   label22->set_use_markup(true);
   label22->set_selectable(false);
   frame6->set_shadow_type(Gtk::SHADOW_NONE);
   frame6->set_label_align(0,0.5);
   frame6->add(*alignment6);
   frame6->set_label_widget(*label22);
   table5->set_row_spacings(0);
   table5->set_col_spacings(0);
   table5->attach(*checkbutton1, 0, 1, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table5->attach(*frame6, 0, 1, 1, 2, Gtk::FILL, Gtk::EXPAND|Gtk::FILL, 0, 0);
   alignment5->add(*table5);
   label21->set_alignment(0.5,0.5);
   label21->set_padding(0,0);
   label21->set_justify(Gtk::JUSTIFY_LEFT);
   label21->set_line_wrap(false);
   label21->set_use_markup(true);
   label21->set_selectable(false);
   frame5->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame5->set_label_align(0,0.5);
   frame5->add(*alignment5);
   frame5->set_label_widget(*label21);
   label20->set_alignment(0.5,0.5);
   label20->set_padding(0,0);
   label20->set_justify(Gtk::JUSTIFY_LEFT);
   label20->set_line_wrap(false);
   label20->set_use_markup(false);
   label20->set_selectable(false);
   notebook1->set_flags(Gtk::CAN_FOCUS);
   notebook1->set_show_tabs(true);
   notebook1->set_show_border(true);
   notebook1->set_tab_pos(Gtk::POS_TOP);
   notebook1->set_scrollable(false);
   notebook1->append_page(*frame2, *label7);
   notebook1->pages().back().set_tab_label_packing(false, true, Gtk::PACK_START);
   notebook1->append_page(*vbox1, *label1);
   notebook1->pages().back().set_tab_label_packing(false, true, Gtk::PACK_START);
   notebook1->append_page(*frame4, *label16);
   notebook1->pages().back().set_tab_label_packing(false, true, Gtk::PACK_START);
   notebook1->append_page(*frame5, *label20);
   notebook1->pages().back().set_tab_label_packing(false, true, Gtk::PACK_START);
   dlg_konfigurasi->get_vbox()->set_homogeneous(false);
   dlg_konfigurasi->get_vbox()->set_spacing(0);
   dlg_konfigurasi->get_vbox()->pack_start(*notebook1);
   dlg_konfigurasi->set_title(_("Konfigurasi "));
   dlg_konfigurasi->set_modal(true);
   dlg_konfigurasi->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dlg_konfigurasi->set_resizable(true);
   dlg_konfigurasi->property_destroy_with_parent().set_value(false);
   dlg_konfigurasi->set_has_separator(true);
   dlg_konfigurasi->add_action_widget(*cancelbutton1, -6);
   dlg_konfigurasi->add_action_widget(*okbutton1, -5);
   cancelbutton1->show();
   okbutton1->show();
   radio_mode_server->show();
   radio_mode_monitor->show();
   label14->show();
   label15->show();
   check_autostart->show();
   hseparator1->show();
   table3->show();
   alignment2->show();
   label8->show();
   frame2->show();
   label7->show();
   label_server_mode->show();
   label4->show();
   label5->show();
   spin_periode_simpan->show();
   label6->show();
   spin_periode_logging->show();
   table1->show();
   alignment1->show();
   label3->show();
   frame1->show();
   label10->show();
   label11->show();
   spin_refresh_list->show();
   label12->show();
   spin_refresh_grafik->show();
   label13->show();
   table2->show();
   alignment3->show();
   label9->show();
   frame3->show();
   vbox1->show();
   label1->show();
   label18->show();
   label19->show();
   spin_periode_db_temp->show();
   table4->show();
   alignment4->show();
   label17->show();
   frame4->show();
   label16->show();
   checkbutton1->show();
   radiobutton1->show();
   radiobutton2->show();
   radiobutton3->show();
   vbox2->show();
   alignment6->show();
   label22->show();
   frame6->show();
   table5->show();
   alignment5->show();
   label21->show();
   frame5->show();
   label20->show();
   notebook1->show();
   dlg_konfigurasi->show();
}

dlg_konfigurasi_glade::~dlg_konfigurasi_glade()
{  delete gmm_data;
}
