// generated 2008/9/8 12:33:45 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_edit_data.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dlg_edit_data_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/table.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#include <gtkmm/box.h>

dlg_edit_data_glade::dlg_edit_data_glade(
)
{  
   
   Gtk::Dialog *dlg_edit_data = this;
   gmm_data = new GlademmData(get_accel_group());
   
   Gtk::Button *cancelbutton6 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   Gtk::Button *okbutton6 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   Gtk::Label *label37 = Gtk::manage(new class Gtk::Label(_("Data")));
   entry_data = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label_satuan = Gtk::manage(new class Gtk::Label(_("<satuan>")));
   label_waktu = Gtk::manage(new class Gtk::Label(_("<waktu data>")));
   
   Gtk::Label *label39 = Gtk::manage(new class Gtk::Label(_("Waktu ")));
   Gtk::Table *table7 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment13 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label36 = Gtk::manage(new class Gtk::Label(_("Informasi Data")));
   Gtk::Frame *frame8 = Gtk::manage(new class Gtk::Frame());
   Gtk::Label *label42 = Gtk::manage(new class Gtk::Label(_("Sumber Data ")));
   label_sumber_data = Gtk::manage(new class Gtk::Label(_("<sumber data>")));
   
   Gtk::Label *label44 = Gtk::manage(new class Gtk::Label(_("Nomer Board ")));
   label_no_board = Gtk::manage(new class Gtk::Label(_("<nomer board>")));
   
   Gtk::Label *label46 = Gtk::manage(new class Gtk::Label(_("Nomer Kanal: ")));
   label_nomer_kanal = Gtk::manage(new class Gtk::Label(_("<nomer kanal>")));
   
   Gtk::Table *table8 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Alignment *alignment14 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label41 = Gtk::manage(new class Gtk::Label(_("Informasi Sumber Data")));
   Gtk::Frame *frame9 = Gtk::manage(new class Gtk::Frame());
   cancelbutton6->set_flags(Gtk::CAN_FOCUS);
   cancelbutton6->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton6->set_relief(Gtk::RELIEF_NORMAL);
   okbutton6->set_flags(Gtk::CAN_FOCUS);
   okbutton6->set_flags(Gtk::CAN_DEFAULT);
   okbutton6->set_relief(Gtk::RELIEF_NORMAL);
   dlg_edit_data->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   label37->set_alignment(0,0.5);
   label37->set_padding(0,0);
   label37->set_justify(Gtk::JUSTIFY_LEFT);
   label37->set_line_wrap(false);
   label37->set_use_markup(false);
   label37->set_selectable(false);
   entry_data->set_flags(Gtk::CAN_FOCUS);
   entry_data->set_visibility(true);
   entry_data->set_editable(true);
   entry_data->set_max_length(0);
   entry_data->set_text(_(""));
   entry_data->set_has_frame(true);
   entry_data->set_activates_default(false);
   label_satuan->set_alignment(0,0.5);
   label_satuan->set_padding(0,0);
   label_satuan->set_justify(Gtk::JUSTIFY_LEFT);
   label_satuan->set_line_wrap(false);
   label_satuan->set_use_markup(false);
   label_satuan->set_selectable(false);
   label_waktu->set_alignment(0,0.5);
   label_waktu->set_padding(0,0);
   label_waktu->set_justify(Gtk::JUSTIFY_LEFT);
   label_waktu->set_line_wrap(false);
   label_waktu->set_use_markup(false);
   label_waktu->set_selectable(false);
   label39->set_alignment(0,0.5);
   label39->set_padding(0,0);
   label39->set_justify(Gtk::JUSTIFY_LEFT);
   label39->set_line_wrap(false);
   label39->set_use_markup(false);
   label39->set_selectable(false);
   table7->set_row_spacings(0);
   table7->set_col_spacings(0);
   table7->attach(*label37, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table7->attach(*entry_data, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table7->attach(*label_satuan, 2, 3, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table7->attach(*label_waktu, 1, 2, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table7->attach(*label39, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   alignment13->add(*table7);
   label36->set_alignment(0.5,0.5);
   label36->set_padding(0,0);
   label36->set_justify(Gtk::JUSTIFY_LEFT);
   label36->set_line_wrap(false);
   label36->set_use_markup(true);
   label36->set_selectable(false);
   frame8->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame8->set_label_align(0,0.5);
   frame8->add(*alignment13);
   frame8->set_label_widget(*label36);
   label42->set_alignment(0,0.5);
   label42->set_padding(0,0);
   label42->set_justify(Gtk::JUSTIFY_LEFT);
   label42->set_line_wrap(false);
   label42->set_use_markup(false);
   label42->set_selectable(false);
   label_sumber_data->set_alignment(0,0.5);
   label_sumber_data->set_padding(0,0);
   label_sumber_data->set_justify(Gtk::JUSTIFY_LEFT);
   label_sumber_data->set_line_wrap(false);
   label_sumber_data->set_use_markup(false);
   label_sumber_data->set_selectable(false);
   label44->set_alignment(0,0.5);
   label44->set_padding(0,0);
   label44->set_justify(Gtk::JUSTIFY_LEFT);
   label44->set_line_wrap(false);
   label44->set_use_markup(false);
   label44->set_selectable(false);
   label_no_board->set_alignment(0,0.5);
   label_no_board->set_padding(0,0);
   label_no_board->set_justify(Gtk::JUSTIFY_LEFT);
   label_no_board->set_line_wrap(false);
   label_no_board->set_use_markup(false);
   label_no_board->set_selectable(false);
   label46->set_alignment(0,0.5);
   label46->set_padding(0,0);
   label46->set_justify(Gtk::JUSTIFY_LEFT);
   label46->set_line_wrap(false);
   label46->set_use_markup(false);
   label46->set_selectable(false);
   label_nomer_kanal->set_alignment(0,0.5);
   label_nomer_kanal->set_padding(0,0);
   label_nomer_kanal->set_justify(Gtk::JUSTIFY_LEFT);
   label_nomer_kanal->set_line_wrap(false);
   label_nomer_kanal->set_use_markup(false);
   label_nomer_kanal->set_selectable(false);
   table8->set_row_spacings(0);
   table8->set_col_spacings(0);
   table8->attach(*label42, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*label_sumber_data, 1, 2, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*label44, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*label_no_board, 1, 2, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*label46, 0, 1, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table8->attach(*label_nomer_kanal, 1, 2, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   alignment14->add(*table8);
   label41->set_alignment(0.5,0.5);
   label41->set_padding(0,0);
   label41->set_justify(Gtk::JUSTIFY_LEFT);
   label41->set_line_wrap(false);
   label41->set_use_markup(true);
   label41->set_selectable(false);
   frame9->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame9->set_label_align(0,0.5);
   frame9->add(*alignment14);
   frame9->set_label_widget(*label41);
   dlg_edit_data->get_vbox()->set_homogeneous(false);
   dlg_edit_data->get_vbox()->set_spacing(0);
   dlg_edit_data->get_vbox()->pack_start(*frame8);
   dlg_edit_data->get_vbox()->pack_start(*frame9);
   dlg_edit_data->set_title(_("Informasi Data"));
   dlg_edit_data->set_modal(false);
   dlg_edit_data->property_window_position().set_value(Gtk::WIN_POS_NONE);
   dlg_edit_data->set_resizable(true);
   dlg_edit_data->property_destroy_with_parent().set_value(false);
   dlg_edit_data->set_has_separator(true);
   dlg_edit_data->add_action_widget(*cancelbutton6, -6);
   dlg_edit_data->add_action_widget(*okbutton6, -5);
   cancelbutton6->show();
   okbutton6->show();
   label37->show();
   entry_data->show();
   label_satuan->show();
   label_waktu->show();
   label39->show();
   table7->show();
   alignment13->show();
   label36->show();
   frame8->show();
   label42->show();
   label_sumber_data->show();
   label44->show();
   label_no_board->show();
   label46->show();
   label_nomer_kanal->show();
   table8->show();
   alignment14->show();
   label41->show();
   frame9->show();
   dlg_edit_data->show();
}

dlg_edit_data_glade::~dlg_edit_data_glade()
{  delete gmm_data;
}
