// generated 2008/9/12 23:20:51 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_koneksi_sumber.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_koneksi_sumber.hh and.//dlg_koneksi_sumber.cc

#ifndef _DLG_KONEKSI_SUMBER_GLADE_HH
#  define _DLG_KONEKSI_SUMBER_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/label.h>
#include <gtkmm/combobox.h>
#include <gtkmm/treeview.h>

class dlg_koneksi_sumber_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * dlg_koneksi_sumber;
        class Gtk::Button * okbutton1;
        class Gtk::Label * label_nama_sumber;
        class Gtk::ComboBox * combo_port;
        class Gtk::TreeView * treeview2;
protected:
        
        dlg_koneksi_sumber_glade();
        
        ~dlg_koneksi_sumber_glade();
private:
        virtual void on_okbutton1_clicked() = 0;
};
#endif
