// generated 2008/11/21 19:20:26 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_edit_sumber.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_edit_sumber.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "dlg_edit_sumber_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/adjustment.h>
#include <gtkmm/table.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/fixed.h>
#include <gtkmm/frame.h>
#include <gtkmm/button.h>

dlg_edit_sumber_glade::dlg_edit_sumber_glade(
)
{  
   
   Gtk::Dialog *dlg_edit_sumber = this;
   gmm_data = new GlademmData(get_accel_group());
   button_cancel = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   button_ok = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));
   
   Gtk::Label *label15 = Gtk::manage(new class Gtk::Label(_("Jumlah Kanal")));
   Gtk::Adjustment *spinbutton1_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 100, 1, 10, 10));
   spinbutton1 = Gtk::manage(new class Gtk::SpinButton(*spinbutton1_adj, 1, 0));
   check_sumber_aktif = Gtk::manage(new class Gtk::CheckButton(_("Sumber Data Aktif")));
   entry_nama_sumber = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Label *label12 = Gtk::manage(new class Gtk::Label(_("Nama Sumber Data")));
   Gtk::Table *table2 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::RadioButton::Group _RadioBGroup_radio_modul;
   radio_modul = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_modul, _("_Monita Modul"), true));
   radio_pm_server = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_modul, _("Power Meter Server")));
   radio_gsm = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_modul, _("GSM/HP")));
   radio_server = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_modul, _("Database")));
   radio_file = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radio_modul, _("Email (monitor directory)")));
   
   Gtk::VBox *vbox3 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Alignment *alignment3 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label16 = Gtk::manage(new class Gtk::Label(_("Jenis Sumber Data")));
   frame3 = Gtk::manage(new class Gtk::Frame());
   entry_ip_address = Gtk::manage(new class Gtk::Entry());
   entry_port = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Adjustment *spin_no_stack_adj = Gtk::manage(new class Gtk::Adjustment(1, 1, 5, 1, 10, 10));
   spin_no_stack = Gtk::manage(new class Gtk::SpinButton(*spin_no_stack_adj, 1, 0));
   
   Gtk::Label *label13 = Gtk::manage(new class Gtk::Label(_("IP Address")));
   Gtk::Label *label14 = Gtk::manage(new class Gtk::Label(_("IP Port")));
   Gtk::Label *label17 = Gtk::manage(new class Gtk::Label(_("Nomer Modul/Port")));
   Gtk::Fixed *fixed1 = Gtk::manage(new class Gtk::Fixed());
   Gtk::Alignment *alignment2 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label11 = Gtk::manage(new class Gtk::Label(_("Parameter")));
   Gtk::Frame *frame2 = Gtk::manage(new class Gtk::Frame());
   Gtk::Label *label_page_modul = Gtk::manage(new class Gtk::Label(_("Modul")));
   Gtk::Label *label19 = Gtk::manage(new class Gtk::Label(_("Direktori ")));
   entry_directory = Gtk::manage(new class Gtk::Entry());
   
   Gtk::Button *button1 = Gtk::manage(new class Gtk::Button(_("_Browse"), true));
   Gtk::Table *table1 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Label *label_page_email = Gtk::manage(new class Gtk::Label(_("Email (monitor direktori)")));
   notebook_parameter = Gtk::manage(new class Gtk::Notebook());
   
   Gtk::VBox *vbox2 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Alignment *alignment1 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   Gtk::Label *label7 = Gtk::manage(new class Gtk::Label(_("Sumber Data")));
   frame1 = Gtk::manage(new class Gtk::Frame());
   button_cancel->set_flags(Gtk::CAN_FOCUS);
   button_cancel->set_flags(Gtk::CAN_DEFAULT);
   button_cancel->set_relief(Gtk::RELIEF_NORMAL);
   button_ok->set_flags(Gtk::CAN_FOCUS);
   button_ok->set_flags(Gtk::CAN_DEFAULT);
   button_ok->set_relief(Gtk::RELIEF_NORMAL);
   dlg_edit_sumber->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   label15->set_size_request(88,16);
   label15->set_alignment(0.5,0.5);
   label15->set_padding(0,0);
   label15->set_justify(Gtk::JUSTIFY_LEFT);
   label15->set_line_wrap(false);
   label15->set_use_markup(false);
   label15->set_selectable(false);
   spinbutton1->set_size_request(56,26);
   spinbutton1->set_flags(Gtk::CAN_FOCUS);
   spinbutton1->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton1->set_numeric(false);
   spinbutton1->set_digits(0);
   spinbutton1->set_wrap(false);
   check_sumber_aktif->set_size_request(192,24);
   check_sumber_aktif->set_flags(Gtk::CAN_FOCUS);
   check_sumber_aktif->set_relief(Gtk::RELIEF_NORMAL);
   check_sumber_aktif->set_mode(true);
   check_sumber_aktif->set_active(false);
   entry_nama_sumber->set_size_request(160,26);
   entry_nama_sumber->set_flags(Gtk::CAN_FOCUS);
   entry_nama_sumber->set_visibility(true);
   entry_nama_sumber->set_editable(true);
   entry_nama_sumber->set_max_length(0);
   entry_nama_sumber->set_text(_(""));
   entry_nama_sumber->set_has_frame(true);
   entry_nama_sumber->set_activates_default(false);
   label12->set_size_request(120,16);
   label12->set_alignment(0.5,0.5);
   label12->set_padding(0,0);
   label12->set_justify(Gtk::JUSTIFY_LEFT);
   label12->set_line_wrap(false);
   label12->set_use_markup(false);
   label12->set_selectable(false);
   table2->set_row_spacings(0);
   table2->set_col_spacings(0);
   table2->attach(*label15, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*spinbutton1, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*check_sumber_aktif, 1, 2, 2, 3, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*entry_nama_sumber, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table2->attach(*label12, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   radio_modul->set_flags(Gtk::CAN_FOCUS);
   radio_modul->set_relief(Gtk::RELIEF_NORMAL);
   radio_modul->set_mode(true);
   radio_modul->set_active(true);
   radio_pm_server->set_flags(Gtk::CAN_FOCUS);
   radio_pm_server->set_relief(Gtk::RELIEF_NORMAL);
   radio_pm_server->set_mode(true);
   radio_pm_server->set_active(false);
   radio_gsm->set_sensitive(false);
   radio_gsm->set_flags(Gtk::CAN_FOCUS);
   radio_gsm->set_border_width(1);
   radio_gsm->set_relief(Gtk::RELIEF_NORMAL);
   radio_gsm->set_mode(true);
   radio_gsm->set_active(false);
   radio_server->set_sensitive(false);
   radio_server->set_flags(Gtk::CAN_FOCUS);
   radio_server->set_relief(Gtk::RELIEF_NORMAL);
   radio_server->set_mode(true);
   radio_server->set_active(false);
   radio_file->set_flags(Gtk::CAN_FOCUS);
   radio_file->set_relief(Gtk::RELIEF_NORMAL);
   radio_file->set_mode(true);
   radio_file->set_active(false);
   vbox3->pack_start(*radio_modul, Gtk::PACK_SHRINK, 0);
   vbox3->pack_start(*radio_pm_server, Gtk::PACK_SHRINK, 0);
   vbox3->pack_start(*radio_gsm, Gtk::PACK_SHRINK, 0);
   vbox3->pack_start(*radio_server, Gtk::PACK_SHRINK, 0);
   vbox3->pack_start(*radio_file, Gtk::PACK_SHRINK, 0);
   alignment3->add(*vbox3);
   label16->set_alignment(0.5,0.5);
   label16->set_padding(0,0);
   label16->set_justify(Gtk::JUSTIFY_LEFT);
   label16->set_line_wrap(false);
   label16->set_use_markup(true);
   label16->set_selectable(false);
   frame3->set_border_width(5);
   frame3->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame3->set_label_align(0,0.5);
   frame3->add(*alignment3);
   frame3->set_label_widget(*label16);
   entry_ip_address->set_size_request(160,26);
   entry_ip_address->set_flags(Gtk::CAN_FOCUS);
   entry_ip_address->set_visibility(true);
   entry_ip_address->set_editable(true);
   entry_ip_address->set_max_length(0);
   entry_ip_address->set_text(_(""));
   entry_ip_address->set_has_frame(true);
   entry_ip_address->set_activates_default(false);
   entry_port->set_size_request(160,26);
   entry_port->set_flags(Gtk::CAN_FOCUS);
   entry_port->set_visibility(true);
   entry_port->set_editable(true);
   entry_port->set_max_length(0);
   entry_port->set_text(_(""));
   entry_port->set_has_frame(true);
   entry_port->set_activates_default(false);
   spin_no_stack->set_size_request(56,26);
   spin_no_stack->set_flags(Gtk::CAN_FOCUS);
   spin_no_stack->set_update_policy(Gtk::UPDATE_ALWAYS);
   spin_no_stack->set_numeric(false);
   spin_no_stack->set_digits(0);
   spin_no_stack->set_wrap(false);
   label13->set_size_request(128,16);
   label13->set_alignment(0.5,0.5);
   label13->set_padding(0,0);
   label13->set_justify(Gtk::JUSTIFY_LEFT);
   label13->set_line_wrap(true);
   label13->set_use_markup(false);
   label13->set_selectable(false);
   label14->set_size_request(41,16);
   label14->set_alignment(0.5,0.5);
   label14->set_padding(0,0);
   label14->set_justify(Gtk::JUSTIFY_LEFT);
   label14->set_line_wrap(false);
   label14->set_use_markup(false);
   label14->set_selectable(false);
   label17->set_size_request(120,16);
   label17->set_alignment(0.5,0.5);
   label17->set_padding(0,0);
   label17->set_justify(Gtk::JUSTIFY_LEFT);
   label17->set_line_wrap(false);
   label17->set_use_markup(false);
   label17->set_selectable(false);
   fixed1->put(*entry_ip_address, 144, 8);
   fixed1->put(*entry_port, 144, 40);
   fixed1->put(*spin_no_stack, 144, 72);
   fixed1->put(*label13, 8, 16);
   fixed1->put(*label14, 8, 48);
   fixed1->put(*label17, 8, 80);
   alignment2->add(*fixed1);
   label11->set_alignment(0.5,0.5);
   label11->set_padding(0,0);
   label11->set_justify(Gtk::JUSTIFY_LEFT);
   label11->set_line_wrap(false);
   label11->set_use_markup(true);
   label11->set_selectable(false);
   frame2->set_border_width(5);
   frame2->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame2->set_label_align(0,0.5);
   frame2->add(*alignment2);
   frame2->set_label_widget(*label11);
   label_page_modul->set_alignment(0.5,0.5);
   label_page_modul->set_padding(0,0);
   label_page_modul->set_justify(Gtk::JUSTIFY_LEFT);
   label_page_modul->set_line_wrap(false);
   label_page_modul->set_use_markup(false);
   label_page_modul->set_selectable(false);
   label19->set_alignment(0,0.5);
   label19->set_padding(0,0);
   label19->set_justify(Gtk::JUSTIFY_LEFT);
   label19->set_line_wrap(false);
   label19->set_use_markup(false);
   label19->set_selectable(false);
   entry_directory->set_flags(Gtk::CAN_FOCUS);
   entry_directory->set_visibility(true);
   entry_directory->set_editable(true);
   entry_directory->set_max_length(0);
   entry_directory->set_text(_(""));
   entry_directory->set_has_frame(true);
   entry_directory->set_activates_default(false);
   button1->set_flags(Gtk::CAN_FOCUS);
   button1->set_relief(Gtk::RELIEF_NORMAL);
   table1->set_row_spacings(0);
   table1->set_col_spacings(0);
   table1->attach(*label19, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*entry_directory, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*button1, 2, 3, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   label_page_email->set_alignment(0.48,0.5);
   label_page_email->set_padding(0,0);
   label_page_email->set_justify(Gtk::JUSTIFY_LEFT);
   label_page_email->set_line_wrap(false);
   label_page_email->set_use_markup(false);
   label_page_email->set_selectable(false);
   notebook_parameter->set_flags(Gtk::CAN_FOCUS);
   notebook_parameter->set_show_tabs(true);
   notebook_parameter->set_show_border(true);
   notebook_parameter->set_tab_pos(Gtk::POS_TOP);
   notebook_parameter->set_scrollable(false);
   notebook_parameter->append_page(*frame2, *label_page_modul);
   notebook_parameter->pages().back().set_tab_label_packing(false, true, Gtk::PACK_START);
   notebook_parameter->append_page(*table1, *label_page_email);
   notebook_parameter->pages().back().set_tab_label_packing(false, true, Gtk::PACK_START);
   vbox2->pack_start(*table2);
   vbox2->pack_start(*frame3, Gtk::PACK_SHRINK, 0);
   vbox2->pack_start(*notebook_parameter, Gtk::PACK_EXPAND_WIDGET, 4);
   alignment1->add(*vbox2);
   label7->set_alignment(0.5,0.5);
   label7->set_padding(0,0);
   label7->set_justify(Gtk::JUSTIFY_LEFT);
   label7->set_line_wrap(false);
   label7->set_use_markup(true);
   label7->set_selectable(false);
   frame1->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame1->set_label_align(0,0.5);
   frame1->add(*alignment1);
   frame1->set_label_widget(*label7);
   dlg_edit_sumber->get_vbox()->set_homogeneous(false);
   dlg_edit_sumber->get_vbox()->set_spacing(0);
   dlg_edit_sumber->get_vbox()->pack_start(*frame1, Gtk::PACK_EXPAND_WIDGET, 10);
   dlg_edit_sumber->set_title(_("Edit Sumber Data"));
   dlg_edit_sumber->set_modal(true);
   dlg_edit_sumber->property_window_position().set_value(Gtk::WIN_POS_CENTER_ON_PARENT);
   dlg_edit_sumber->set_resizable(false);
   dlg_edit_sumber->property_destroy_with_parent().set_value(false);
   dlg_edit_sumber->set_has_separator(true);
   dlg_edit_sumber->add_action_widget(*button_cancel, -6);
   dlg_edit_sumber->add_action_widget(*button_ok, -5);
   button_cancel->show();
   button_ok->show();
   label15->show();
   spinbutton1->show();
   check_sumber_aktif->show();
   entry_nama_sumber->show();
   label12->show();
   table2->show();
   radio_modul->show();
   radio_pm_server->show();
   radio_gsm->show();
   radio_server->show();
   radio_file->show();
   vbox3->show();
   alignment3->show();
   label16->show();
   frame3->show();
   entry_ip_address->show();
   entry_port->show();
   spin_no_stack->show();
   label13->show();
   label14->show();
   label17->show();
   fixed1->show();
   alignment2->show();
   label11->show();
   frame2->show();
   label_page_modul->show();
   label19->show();
   entry_directory->show();
   button1->show();
   table1->show();
   label_page_email->show();
   notebook_parameter->show();
   vbox2->show();
   alignment1->show();
   label7->show();
   frame1->show();
   dlg_edit_sumber->show();
   button_cancel->signal_clicked().connect(SigC::slot(*this, &dlg_edit_sumber_glade::on_button_cancel_clicked), false);
   button_ok->signal_clicked().connect(SigC::slot(*this, &dlg_edit_sumber_glade::on_button_ok_clicked), false);
   radio_modul->signal_toggled().connect(SigC::slot(*this, &dlg_edit_sumber_glade::on_radio_modul_toggled), false);
   radio_pm_server->signal_toggled().connect(SigC::slot(*this, &dlg_edit_sumber_glade::on_radio_pm_server_toggled), false);
   radio_file->signal_group_changed().connect(SigC::slot(*this, &dlg_edit_sumber_glade::on_radio_file_group_changed), false);
   radio_file->signal_toggled().connect(SigC::slot(*this, &dlg_edit_sumber_glade::on_radio_file_toggled), false);
   button1->signal_clicked().connect(SigC::slot(*this, &dlg_edit_sumber_glade::on_button1_clicked), false);
}

dlg_edit_sumber_glade::~dlg_edit_sumber_glade()
{  delete gmm_data;
}
