// generated 2008/10/30 8:28:53 CIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_konfigurasi.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_konfigurasi.hh and.//dlg_konfigurasi.cc

#ifndef _DLG_KONFIGURASI_GLADE_HH
#  define _DLG_KONFIGURASI_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/spinbutton.h>

class dlg_konfigurasi_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::RadioButton * radio_mode_server;
        class Gtk::RadioButton * radio_mode_monitor;
        class Gtk::CheckButton * check_autostart;
        class Gtk::SpinButton * spin_periode_simpan;
        class Gtk::SpinButton * spin_periode_logging;
        class Gtk::SpinButton * spin_refresh_list;
        class Gtk::SpinButton * spin_refresh_grafik;
        class Gtk::SpinButton * spin_periode_db_temp;
protected:
        
        dlg_konfigurasi_glade();
        
        ~dlg_konfigurasi_glade();
};
#endif
