// generated 2008/11/21 19:20:26 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Monita/src/dlg_edit_sumber.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//dlg_edit_sumber.hh and.//dlg_edit_sumber.cc

#ifndef _DLG_EDIT_SUMBER_GLADE_HH
#  define _DLG_EDIT_SUMBER_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/frame.h>
#include <gtkmm/notebook.h>

class dlg_edit_sumber_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Button * button_cancel;
        class Gtk::Button * button_ok;
        class Gtk::SpinButton * spinbutton1;
        class Gtk::CheckButton * check_sumber_aktif;
        class Gtk::Entry * entry_nama_sumber;
        class Gtk::RadioButton * radio_modul;
        class Gtk::RadioButton * radio_pm_server;
        class Gtk::RadioButton * radio_gsm;
        class Gtk::RadioButton * radio_server;
        class Gtk::RadioButton * radio_file;
        class Gtk::Frame * frame3;
        class Gtk::Entry * entry_ip_address;
        class Gtk::Entry * entry_port;
        class Gtk::SpinButton * spin_no_stack;
        class Gtk::Entry * entry_directory;
        class Gtk::Notebook * notebook_parameter;
        class Gtk::Frame * frame1;
protected:
        
        dlg_edit_sumber_glade();
        
        ~dlg_edit_sumber_glade();
private:
        virtual void on_button_cancel_clicked() = 0;
        virtual void on_button_ok_clicked() = 0;
        virtual void on_radio_modul_toggled() = 0;
        virtual void on_radio_pm_server_toggled() = 0;
        virtual void on_radio_file_group_changed() = 0;
        virtual void on_radio_file_toggled() = 0;
        virtual void on_button1_clicked() = 0;
};
#endif
