# generated 2009/6/1 12:22:39 WIT by herry@LancarJaya.(none)
# using glademm V2.6.0

SUBDIRS = po  

EXTRA_DIST = AUTHORS TODO README configure 
le.am_new
bin_PROGRAMS = dl_edit_titik

dl_edit_titik_SOURCES = \
	dl_edit_titik.cc\
	dlg_edit_titik_glade.cc \
	dlg_edit_titik.cc 

noinst_HEADERS = \
	dlg_edit_titik_glade.hh \
	dlg_edit_titik.hh 

AM_CXXFLAGS = @GTKMM_CFLAGS@ 

dl_edit_titik_LDADD = @LIBS@ @GTKMM_LIBS@ 
