// generated 2008/7/31 8:00:50 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Documents/Program/MonitaApp/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//menu1.hh and.//menu1.cc

#ifndef _MENU1_GLADE_HH
#  define _MENU1_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/menu.h>
#include <gtkmm/imagemenuitem.h>

class menu1_glade : public Gtk::Menu
{  
public:
        
        class Gtk::Menu * menu1;
        class Gtk::ImageMenuItem * popup_edit1;
protected:
        
        menu1_glade(GlademmData *gmm_data);
        
        ~menu1_glade();
private:
        virtual void on_popup_edit1_activate() = 0;
};
#endif
