// generated 2008/7/31 8:00:50 WIT by herry@LancarJaya.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/herry/Documents/Program/MonitaApp/src/monitaapp.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in .//menu1.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "menu1_glade.hh"
#include <gtk/gtkimagemenuitem.h>

menu1_glade::menu1_glade(GlademmData *gmm_data
)
{  menu1 = this;
   popup_edit1 = NULL;
   
   
   menu1->items().push_back(Gtk::Menu_Helpers::StockMenuElem(Gtk::StockID("gtk-edit")));
   popup_edit1 = (Gtk::ImageMenuItem *)&menu1->items().back();
   popup_edit1->show();
   popup_edit1->signal_activate().connect(SigC::slot(*this, &menu1_glade::on_popup_edit1_activate), false);
}

menu1_glade::~menu1_glade()
{  
}
